<link rel="stylesheet" href="{{ asset('dist-admin/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist-admin/css/font_awesome_5_free.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist-admin/css/select2.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist-admin/css/bootstrap-tagsinput.css') }}">
<link rel="stylesheet" href="{{ asset('dist-admin/css/duotone-dark.css') }}">
<link rel="stylesheet" href="{{ asset('dist-admin/css/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist-admin/css/iziToast.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist-admin/css/fontawesome-iconpicker.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist-admin/css/bootstrap4-toggle.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist-admin/css/style.css') }}">
<link rel="stylesheet" href="{{ asset('dist-admin/css/components.css') }}">
<link rel="stylesheet" href="{{ asset('dist-admin/css/air-datepicker.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist-admin/css/spacing.css') }}">
<link rel="stylesheet" href="{{ asset('dist-admin/css/custom.css') }}">